In [1]:
from numpy import array

# this loads some HTML style files
from IPython.core.display import HTML
with open( './style/custom.css', 'r' ) as f: html_style = f.read()
HTML( html_style )

# Le matrici

Una matrice di dimensione $n\times m$ è un rettangolo di numeri. Per esempio questa è una matrice $2\times 3$

\begin{bmatrix}
  2.0 &  2.0 &  3.0\\
  1.0 &  3.0 &  4.0
\end{bmatrix}

Diremo che ha 2 <mark>righe</mark> e 3 <mark>colonne</mark>.

Tra matrici è definita la <mark>somma</mark> ed il <mark>prodotto per uno scalare</mark> in modo del tutto analogo a come fatto per i vettori. N.B. la somma è definita solo tra matrici della stessa dimensione. 

# Trasposizione di matrici

La <mark>trasposta</mark> di una matrice si ottiene trasformando le righe in colonne (la 1$^\rm a$ riga diventa la 1$^\rm a$ colonna la 2$^\rm a$ riga diventa la 2$^\rm a$ colonna e così via). Una matrice $n\times m$ diventa una matrice $m\times n$. La trasposta di una matrice si indica con l'apice T. Per esempio

$$
\begin{bmatrix}
  2.0 &  2.0 &  3.0\\
  1.0 &  3.0 &  4.0\\
\end{bmatrix}^{\rm\ T}
\quad=\quad
\begin{bmatrix}
  2.0 &  1.0\\
  2.0 &  3.0\\
  3.0 &  4.0\\
\end{bmatrix}
$$

N.B. la trasposta della trasposta ̀e la matrice di partenza:

$$
\begin{bmatrix}
  2.0 &  1.0\\
  2.0 &  3.0\\
  3.0 &  4.0\\
\end{bmatrix}^{\rm\ T}
\quad=\quad
\begin{bmatrix}
  2.0 &  2.0 &  3.0\\
  1.0 &  3.0 &  4.0\\
\end{bmatrix}
$$

# Vettori riga e vettori colonna

Una matrice di dimensione $n\times 1$ è chiamata un <mark>vettore colonna</mark>

\begin{bmatrix}
  a_1\\ .\\ .\\ .\\  a_n\\
\end{bmatrix}

Una matrice di dimesione $1\times n$ è chiamata un <mark>vettore riga</mark>

\begin{bmatrix}
  a_1& .& .& .&  a_n\\
\end{bmatrix}

Entrambe queste matrici corrispondono allo stesso vettore. L'operazione di transposizione tranforma un vettore riga in un vettore colonna e viceversa.

$$
\begin{bmatrix}
  1.0\\
  2.0\\
  3.0\\
\end{bmatrix}^{\rm\ T}
\quad=\quad
\begin{bmatrix}
  1.0 &  2.0 &  3.0\\
\end{bmatrix}
$$

e

$$
\begin{bmatrix}
  1.0 &  2.0 &  3.0\\
\end{bmatrix}^{\rm\ T}
\quad=\quad
\begin{bmatrix}
  1.0\\
  2.0\\
  3.0\\
\end{bmatrix}
$$

In `Python` le matrici possono essere *costruite* a partire da una lista di liste. 

In [2]:
A = array(  [ [2.0,  2.0,  3.0],  [1.0,  3.0,  4.0] ] )
A

array([[2., 2., 3.],
       [1., 3., 4.]])

In [3]:
A.shape

(2, 3)

In [4]:
A.T

array([[2., 1.],
       [2., 3.],
       [3., 4.]])

In `Python` i vettori sono una categoria a parte rispetto alle matrici (a priori non sono né vettori riga né vettori colonna). 

In [5]:
v = array( [1.0,  2.0,  3.0, 4.0] )
v.shape

(4,)

Possiamo cambiare l'interpretazione di un vettore forzando la sua `shape`.

In [6]:
v.shape = (1,4)
v

array([[1., 2., 3., 4.]])

In [7]:
v.shape = (4,1)
v

array([[1.],
       [2.],
       [3.],
       [4.]])

# Prodotto di matrici

Il prodotto di due matrici è definito solo se la prima matrice ha tante colonne quante sono le righe della seconda matrice. Ovvero possiamo moltiplicare una matrice $n\times k$ solo per matrici di dimensione $k\times m$. Il risultato sarà una matrice $n\times m$.

Mnemonica: $(n\times k) \cdot (k\times m)\ \ =\ \ n\times m$.


### Esempio: prodotto scalare come moltiplicazione di matrici


Uno dei casi più semplici e importanti è la moltiplicazione di un vettore riga per un vettore colonna, ovvero di una matrice $1\times n$ per una matrice $n\times 1$ che darà come risultato una matrice $1\times 1$ ovvero un numero. 

Lo abbiamo già incontrato con un altro nome:

$$
\begin{bmatrix}
  1 &  2 &  3\\
\end{bmatrix}
\cdot
\begin{bmatrix}
  2\\  3\\  1\\
\end{bmatrix}
\quad=\quad
\begin{bmatrix}
  1\\  2\\  3\\
\end{bmatrix}^{\rm\ T}
\cdot\ 
\begin{bmatrix}
  2\\  3\\  1\\
\end{bmatrix}
\quad=\quad
2+6+3
\quad=\quad
11
$$

### Esempio prodotto matrici $3\times 3$ per $3 \times 1$

$$
\begin{bmatrix}
  1& 2& 3\\
  4& 5& 6\\
  7& 8& 9\\
\end{bmatrix}
\cdot\begin{bmatrix}
  x\\  y\\  z\\
\end{bmatrix}
\quad=\quad
\begin{bmatrix}
  \begin{bmatrix}
  1& 2& 3\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x\\  y\\  z\\
  \end{bmatrix}
  \\
  \begin{bmatrix}
  4& 5& 6\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x\\  y\\  z\\
  \end{bmatrix}
  \\
  \begin{bmatrix}
  7& 8& 9\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x\\  y\\  z\\
  \end{bmatrix}
\end{bmatrix}
\quad=\quad
\begin{bmatrix}
  1x+2y+3z\\
  4x+5y+6z\\
  7x+8y+9z\\
\end{bmatrix}
$$

In [8]:
A  = array( [ [1,2,3], [4,5,6], [7,8,9] ] )
v1 = array( [ [1,0,0] ] ).T
v2 = array( [ [0,1,0] ] ).T
v3 = array( [ [0,0,1] ] ).T
print ( A @ v1 )

[[1]
 [4]
 [7]]


### Esempio prodotto matrici $3\times 3$ per $3 \times 3$

$$
\begin{bmatrix}
  1& 2& 3\\
  4& 5& 6\\
  7& 8& 9\\
\end{bmatrix}
\cdot\begin{bmatrix}
  x1& x2& x3\\
  y1& y2& y3\\
  z1& z2& z3\\
\end{bmatrix}
\quad=\quad
$$

$$=\quad
\begin{bmatrix}
  \begin{bmatrix}
  1& 2& 3\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x1\\  y1\\  z1\\
  \end{bmatrix}
  &
  \begin{bmatrix}
  1& 2& 3\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x2\\  y2\\  z2\\
  \end{bmatrix}
  &
  \begin{bmatrix}
  1& 2& 3\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x3\\  y3\\  z3\\
  \end{bmatrix}
  \\
  \begin{bmatrix}
  4& 5& 6\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x1\\  y1\\  z1\\
  \end{bmatrix}
  &
  \begin{bmatrix}
  4& 5& 6\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x2\\  y2\\  z2\\
  \end{bmatrix}
  &
  \begin{bmatrix}
  4& 5& 6\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x3\\  y3\\  z3\\
  \end{bmatrix}
  \\
  \begin{bmatrix}
  7& 8& 9\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x1\\  y1\\  z1\\
  \end{bmatrix}
  &
  \begin{bmatrix}
  7& 8& 9\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x2\\  y2\\  z2\\
  \end{bmatrix}
  &
  \begin{bmatrix}
  7& 8& 9\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x3\\  y3\\  z3\\
  \end{bmatrix}
\end{bmatrix}
$$

### Esempio

Verifichiamo. In un caso semplice (il vettore colonna $[1,0,0]^{\rm T}$) che applicare consecutivamente due matrici equivale a applicare il prodotto di matrici. 

$$
\begin{bmatrix}
  x1& x2& x3\\
  y1& y2& y3\\
  z1& z2& z3\\
\end{bmatrix}
\cdot
\begin{bmatrix}
  1\\  0\\  0\\
\end{bmatrix}
\quad=\quad
\begin{bmatrix}
  x1\\ y1\\ z1\\
\end{bmatrix}
$$


$$
\begin{bmatrix}
  1& 2& 3\\
  4& 5& 6\\
  7& 8& 9\\
\end{bmatrix}
\cdot
\begin{bmatrix}
  x1\\ y1\\ z1\\
\end{bmatrix}
\quad=\quad
\begin{bmatrix}
  \begin{bmatrix}
  1& 2& 3\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x1\\  y1\\  z1\\
  \end{bmatrix}
  \\
  \begin{bmatrix}
  4& 5& 6\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x1\\  y1\\  z1\\
  \end{bmatrix}
  \\
  \begin{bmatrix}
  7& 8& 9\\
  \end{bmatrix}
  \cdot
  \begin{bmatrix}
  x3\\  y3\\  z3\\
  \end{bmatrix}
\end{bmatrix}
$$