In [2]:
from numpy import array

# this loads some HTML style files
from IPython.core.display import HTML
with open( './style/custom.css', 'r' ) as f: html_style = f.read()
HTML( html_style )

Definiamo:

$$
A
\quad=\quad
\begin{bmatrix}
  2& 3& 4\\
  1& 1& 1\\
  8& 5& 2\\
\end{bmatrix}
$$

e

$$
v
=
\begin{bmatrix}
  2&  1&  2\\
\end{bmatrix}
$$

### Domanda 1

$$
A
\cdot
v^{\rm T}
\quad=\quad
?
$$


### Risposta 1

In [6]:
A = array( [ [2,3,4], [1,1,1], [8,5,2] ] )
v = array( [ [2,1,2] ] )
A @ v.T

array([[15],
       [ 5],
       [25]])

### Domanda 2

$$
v
\cdot
A
\quad=\quad
?
$$


### Risposta 2

In [7]:
v @ A

array([[21, 17, 13]])

### Domanda 3

$$
A^{\rm T}
\quad=\quad
?
$$

### Risposta 3

In [8]:
A.T

array([[2, 1, 8],
       [3, 1, 5],
       [4, 1, 2]])

### Domanda 4

$$
v
\cdot
A^{\rm T}
\quad=\quad
?
$$

### Risposta 4

In [9]:
v @ A.T

array([[15,  5, 25]])