In [23]:
from numpy import array, sqrt

from scipy.stats import binom, nbinom
from scipy.stats import norm as normal # ATTENZIONE non standard
from scipy.stats import t as tstudent  # ATTENZIONE non standard

from statsmodels.stats.proportion import proportion_confint

from scipy.linalg import null_space, det, norm, inv

# this loads some HTML style files
from IPython.core.display import HTML
with open( './style/custom.css', 'r' ) as f: html_style = f.read()
HTML( html_style )

----------------
----------------

### Domanda 1

Sia $v=[-2,3,-1,-1]$.

>  A. Si calcoli $\|v\|$.

### Risposta 1A

$\|v\|=\sqrt{v^{\rm T}\cdot v}=\sqrt{(-2)^2+3^2+(-1)^2+(-1)^2}=\sqrt{15}=3.87$

In [24]:
v = array( [-2,3,-1,-1] )
sqrt( v.T@v ), norm ( v ) # due modi equivalenti

(3.872983346207417, 3.872983346207417)

> B.  Si calcoli $\dfrac{1}{\|v\|}\cdot v$.

### Risposta 1B

$\dfrac{1}{\|v\|}\cdot v = [-0.52,  0.77, -0.26, -0.26]$

In [25]:
v / norm (v)

array([-0.51639778,  0.77459667, -0.25819889, -0.25819889])

>  C. Esistono soluzioni del seguente sistema che non sono mutiple del vettore $v$ ?

$$
\left\{
\begin{array}{rcc}
  -2x+ z+ 3w& = &0\\
  2x+ 3y+ 2z+ 3w & = &0\\ 
  x+ 2y+ 4z & = &0\\
  y+ 3z  & = &0\\
\end{array}
\right.
$$

Per comodità trascrivo la matrice $A$ associata al sistema nella forma di lista di liste.

    [ [-2, 0, 1, 3], 
      [2, 3, 2, 3], 
      [1, 2, 4, 0], 
      [0, 1, 3, 0]  ]

### Risposta 1C

Il vettore $v$ è soluzione del sistema, infatti $A\cdot v^{\rm T}=0$:

In [26]:
A = array( [ [-2, 0, 1, 3], 
             [ 2, 3, 2, 3], 
             [ 1, 2, 4, 0], 
             [ 0, 1, 3, 0]  ] )
A @ v.T

array([0, 0, 0, 0])

Tutte le soluzioni sono multiple di un unico vettore $[−0.52,0.77,−0.26,−0.26]$ quindi non esistono altre soluzioni:

In [27]:
null_space(A)

array([[-0.51639778],
       [ 0.77459667],
       [-0.25819889],
       [-0.25819889]])

-----------------
-----------------

### Domanda 2

Un'urna contiene biglie rosse e blu. Estraiamo 300 biglie (con reimbussolamento) osserviamo  60 biglie rosse. 

>  A.   Si calcoli con una confidenza del $99\%$ un limite inferiore per la proporzione di bigli rosse.

### Risposta 2A

La proporzione di biglie rosse è maggiore del $15\%$ con una confidenza del $99\%$.

In [28]:
proportion_confint(60,300,alpha=2*0.01)

(0.14627529714775228, 0.25372470285224774)

>   B.   Con che p-valore possiamo rigettare l'ipotesi che le biglie rosse sono il $15\%$? 

(Come ipotesi alternativa si prenda l'ipotesi che la proporzione sia $>15\%$.)

### Risposta 2B 

Il p-valore è $<1\%$:

In [29]:
1-binom.cdf(60,300,0.15)

0.007744734232711492

---------------
---------------


### Domanda 3

Marie is getting married tomorrow at an outdoor ceremony in the desert. In recent years it has rained only $8$ days each year. But the weatherman has predicted rain for tomorrow. When it actually rains, the weatherman correctly forecasts rain $85\%$ of the time. When it doesn’t rain, he incorrectly forecasts rain $5\%$ of the times. 

>  A.   What is the probability that it will rain on the day of Marie’s wedding?

### Risposta 3

$R$ event: it rains on Marie’s wedding

$T_+$ event: the weatherman predicts rain

$\Pr(R) =8/365 $ it rains $8$ days out of $365$

$\Pr(T_+|R) = 0.85 $ when it rains, rain is predicted

$\Pr(T_+|\neg R) = 0.05$ when it does not rain,  rain is predicted

$\Pr(T_+) = \Pr(T_+|R)\cdot \Pr(R)+ \Pr(T_+|\neg R)\cdot \Pr(\neg R) = 0.0675$ 

In [30]:
pr_t_pos = 0.85 * 8 / 365 + 0.05 * (365-8) / 365
pr_t_pos

0.06753424657534247

$\Pr(R| T_+)\ =\ \dfrac{\Pr(R)\cdot \Pr(T_+|R)}{\Pr(T_+)}=0.28$ (Risposta) 

In [31]:
risposta = 0.85 * 8 / (365 * pr_t_pos)
risposta

0.27586206896551724

-----------------
-----------------


### Domanda 4

Abbiamo una scatola di viti di cui il $5\%$ è difettoso. I nostri prodotti richiedono $9$ viti
per pezzo. Procediamo nel seguente modo. Prendiamo una vite a caso e, se difettosa, la sostituiamo con
un’altra, anche scelta a caso, fino ad avere le 9 viti richieste.

>  A.  In media quante viti dovremmo provare per completare un pezzo?


### Risposta 2A

Dobbiamo calcolare ${\rm E}(Y+n)$ dove $Y\sim NB(n,p)$ dove $n=9$ e $p=0.95$.

${\rm E}(Y+n)\ =\ {\rm E}(Y)+n\ =\ \dfrac{n(1-p)}{p}+n\ =\ 9.5$

In [32]:
n=9
p=0.95
n*(1-p) / p +9

9.473684210526317

>  B.   Qual è la probabilità di riuscire a finire un pezzo scegliendo ≤ 10 viti?

### Risposta 2B

$\Pr(Y + 9 \le 10)\ =\ \Pr(Y  \le 1)\ =\ 0.91$

In [33]:
nbinom.cdf(1,9,0.95)

0.9138616441006835

>  C.    Quanti tentativi dovremo preventivare perchè la probabilità di finire un pezzo sia almeno il 99%?

### Risposta 2B

Devo calcolare $x$ tale che $\Pr(Y + 9 \le x)\ =\ 0.99$

In [34]:
nbinom.ppf(0.99,9,0.95) + 9

12.0